export enum Source {
  LeagueOfLegends = 'lol',
  LegendsOfRuneterra = 'lor',
  VALORANT = 'val',
  TeamfightTactics = 'tft',
  WildRift = 'wr',
  RiotGames = 'riotgames'
}

export enum Locale {
  English_UnitedStates = 'en-us',
  English_UnitedKingdom = 'en-gb',
  German = 'de-de',
  Spanish_Spain = 'es-es',
  Spanish_Mexico = 'es-mx',
  French = 'fr-fr',
  Italian = 'it-it',
  Polish = 'pl-pl',
  Portuguese_Brazil = 'pt-br',
  Russian = 'ru-ru',
  Turkish = 'tr-tr',
  Japanese = 'ja-jp',
  Korean_SouthKorea = 'ko-kr',
  Chinese_Taiwan = 'zh-tw',
  Thai = 'th-th',
  English_Philippines = 'en-ph',
  English_Singapore = 'en-sg',
  English_Polish = 'en-pl',
  Greek_Greece = 'el-gr',
  Romanian = 'ro-ro',
  Hungarian = 'hu-hu',
  Czech_CzechRepublic = 'cs-cz',
  English_Australia = 'en-au',
  // Spanish_Argentina = "es-ar",
  Vietnamese_Vietnam = 'vi-vn',
  Indonesian = 'id-id',
  Arabic_UnitedArabEmirates = 'ar-ae',
  Malay_Malaysia = 'ms-my',
  Chenese_Malaysia = 'zh-my'
}
