name: lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    name: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install and build
        run: |
          npm install
          npm run build --if-present

      - name: Lint
        run: npm run lint
